### ISSUE TITLE
Reading data files

### ISSUE THREAD

**Issue by dmarkfer** [dmarkfer/MTV3D#7]
UTF-8

**Comment by praka17** [comment]
Hi dmarkfer
Thankyou for creating this great highly useful app.  I am unable to open the attached file  though some other similar meshtal  files are opening properly. It would be of great help if you could help me to understand the reason and to open this file for 3D plotting. 
[mesh1.zip](https://github.com/dmarkfer/MTV3D/files/11638301/mesh1.zip)
Thankyou
